## NumPy library

Installing library

In [2]:
!pip install numpy

Importing the library

In [3]:
import numpy as np

## Creating Arrays

In [46]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)], dtype = float)
c = np.array([[(1,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

print("a: ",a)
print("\n")
print("b: ",b)
print("\n")
print("c: ",c)

a:  [1 2 3]


b:  [[1. 2. 3.]
 [4. 5. 6.]]


c:  [[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]


In [10]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Indexing and Slicing NumPy arrays

**2D Array**


*   first value: index of inner array
*   Second value: index of inner element inside that inner array



In [9]:
print(b[0, 1])
print(b[1])
print(b[1:3, 0:2])
print(b[0:1])

2.0
[4. 5. 6.]
[[4. 5.]]
[[1. 2. 3.]]


**3D Array**


*   first value: index of inner 2D array in first dimension
*   second value: index of inner 1D array in second dimension
*   third value: index of element in third dimension





In [12]:
print(c)

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]


In [13]:
print(c[1,0,2])
print(c[0,1,0])

1.0
4.0


## Shape

In [20]:
print(a)
print(f"Dimension:{a.ndim}, Shape:{a.shape}, Size:{a.size}")

[1 2 3]
Dimension:1, Shape:(3,), Size:3


In [21]:
print(b)
print(f"Dimension:{b.ndim}, Shape:{b.shape}, Size:{b.size}")

[[1. 2. 3.]
 [4. 5. 6.]]
Dimension:2, Shape:(2, 3), Size:6


In [22]:
print(c)
print(f"Dimension:{c.ndim}, Shape:{c.shape}, Size:{c.size}")

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [4. 5. 6.]]]
Dimension:3, Shape:(2, 2, 3), Size:12


## Basic Numpy Functions

**linspace**- Creates an array of n equally spaced values from a to b

Syntax: np.linspace(a, b, n)



In [25]:
np.linspace(2, 3, 7)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

**logspace** - Creates an array of n equally spaced logarithmically values from a to b   
Syntax: **np.logspace(a, b, n)**

In [26]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

**arrange** - Creates arrays of values from a to b with step size of n

Syntax: **np.arrange(a, b, n)**

In [28]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

**zeros** - Creates a 'n x m' array filled with zeros

Syntax: **np.zeros((n,m))**

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**ones** - Creates a 'n x m' array filled with ones

Syntax: **np.ones(n, m)**

In [32]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## Array Append and Delete

 **np.append(arr, list/tuple/element)**

**np.delete(arr, index, axis = 0(for row)/1(for column))**

In [43]:
a = np.append(a, [7,8,9])
print(a)

[1 2 3 7 8 9]


In [44]:
np.delete(a, 2, 0)

array([1, 2, 7, 8, 9])

In [47]:
print(b)
np.delete(b, 2, 1)

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1., 2.],
       [4., 5.]])

## Reshaping the Arrays

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

## Combining Arrays

In [62]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [63]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Array Element-wise Operations

In [64]:
add = arr1 + arr2
dif = arr1 - arr2
mul = arr1 * arr2

In [65]:
print(add)
print(dif)
print(mul)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]


## Aggregating Functions

In [67]:
arr = [1, 2, 3, 4, 5, 6]
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr1))
print(np.std(arr1))
print(np.max(arr1))
print(np.min(arr1))

3.5
3.5
2.9166666666666665
1.707825127659933
6
1


## Finding missing values in the matrix

In [71]:
mat = np.array([[1, np.nan, 3], [4, 5, np.nan]])
np.isnan(mat)

array([[False,  True, False],
       [False, False,  True]])